# Generated by Django 6.0.7 on 2026-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='blocks_served',
            field=models.CharField(default='RV Block, KS Block, BD Block, Mech Block, MBA Block', max_length=255),
        ),
    ]
