# Generated by Django 6.0.7 on 2026-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_busroute_blocks_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='day_order',
            field=models.CharField(blank=True, help_text='e.g. I, II, III, IV, V', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='department',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='section',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
