# Generated by Django 6.0.7 on 2026-07-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_academiccalendar_day_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
