# Generated by Django 6.0.7 on 2026-07-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hostel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
