# Generated by Django 6.0.7 on 2026-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_url',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
