# Generated by Django 6.0.7 on 2026-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_department',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='target_section',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
