# Generated by Django 6.0.7 on 2026-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_target_department_event_target_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_department',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_section',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
