# Generated by Django 6.0.7 on 2026-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_timetable_dayorder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
