# Generated by Django 6.0.7 on 2026-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_studentprofile_semester_timetable_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='semesters',
            field=models.CharField(default='All', help_text='Comma-separated semesters e.g. 1,3,5 or All', max_length=100),
        ),
    ]
