# Generated by Django 6.0.7 on 2026-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_faculty_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
